### ISSUE TITLE
Claustrophobia bug

### ISSUE THREAD

**Issue by will-0** [will-0/will-0.github.io#25]
1) Sheep are able to jump across borders (see image)
2) A couple of times I randomly died, without any sheep near me

Settings: Difficulty 40
Browser: Microsoft Edge

![image](https://user-images.githubusercontent.com/30996474/122253096-c7be1580-cec3-11eb-868e-74ae92f60651.png)

(The sheep in the bottom left got in there after it initially being empty)

**Comment by sam-halfpenny** [comment]
ok i will have a look

**Comment by sam-halfpenny** [comment]
fixed
